
// This maps error constants with error codes.
module.exports = {
    // User related error codes
    INVALID_API_KEY: -101,
    INVALID_TOKEN: -102,
    NO_TOKEN: -103,
    INVALID_USER: -104,
    INVALID_EMAIL_ADDRESS: -105,
    REQUIRED_FIELDS_MISSING: -106,
    LOGIN_FAILED: -107,
    ERROR_IN_USER_ADDITION: -108,
    PASSWORD_DOES_NOT_MATCH: -109,
    CONFIRM_PASSWORD_NOT_SAME: -110,
    ERROR_IN_UPDATE_PASSWORD: -111,
    VERIFICATION_CODE_ERROR: -112,
    ERROR_WHILE_MAIL_SENDING: -113,
    TOKEN_EXPIRED: -114,
    PLEASE_TRY_AGAIN: -115,
    EMAIL_ALREADY_EXIST: -116,
    INVALID_APIKEY: -117,
    IMAGE_FILE_ERROR: -118,
    INVALID_PAGENO_OR_PAGESIZE: -119,
    CONFIRMATION_TOKEN_EXPIRED: -120,
    EMAIL_ID_NOT_REGISTER: -121,
    NO_USER_ROLE_FOUND_IN_DATABASE: -122,
    FETCHING_AGENTS_ERROR: -123,
    CODE_EXPIRED: -124,

    //Device Related error codes
    ADDRESS_FETCH_ERROR: -124,

    NOTIFICATION_DATA_NOT_FOUND: -125,
    NOTIFICATION_NOT_FOUND: -126,
    DELETE_NOTIFICATION_ERROR: -127,
    NOT_ACTIVE_USER: -128,
    INVALID_BOOLEAN_VALUE: -129,
    EMPTY_STRING: -130,
    MISSING_INPUT: -131,
    INVALID_EMAIL_OR_PASSWORD_KEY: -132,
    PASSWORD_MISMATCH_ERROR: -133,
    NOT_APP_USER: -134,

    PLAN_ALREADY_EXIST: -140,
    INSUFFICIENT_PERMISSIONS: -141,
    
    CREATE_DOCUMENT_ERROR: -151,
    BOOK_SHOWING_ERROR: -151,

    // Stripe
    CREATE_CUSTOMER_ERROR: -160,
    CREATE_SUBSCRIPTION_ERROR: -161,
    STORING_STRIPE_DETAILS: -162,
    UPDATE_SUBSCRIPTION_ERROR: -163,
    
    GETTING_DATA: -519,
    STORING_DATA: -520,
    REMOVING_DATA: -521,
    UNKNOWN_ERROR: -522,

    //Http error code.
    HTTP_SUCCESS: 200,
    FOUND: 302,
    NOT_MODIFIED: 304,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    PAYMENT_REQUIRED: 402,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    MEHTOD_NOT_ALLOWED: 404,

    BAD_GATEWAY: 502,

};
